// API Types for Chapter Smith Backend
// Comprehensive TypeScript interfaces for all API endpoints

// YouTube API Related Types
export interface YouTubeVideoInfo {
  id: string;
  title: string;
  description: string;
  duration: string;
  channelTitle: string;
  publishedAt: string;
  thumbnailUrl: string;
  viewCount?: string;
  likeCount?: string;
  url: string;
}

export interface YouTubeTranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

export interface YouTubeTranscriptResponse {
  videoId: string;
  title: string;
  duration: number;
  segments: YouTubeTranscriptSegment[];
  language?: string;
  isAutoGenerated: boolean;
}

// Chapter Generation Types
export interface ChapterGenerationRequest {
  videoId?: string;
  url?: string;
  transcript?: YouTubeTranscriptSegment[];
  options?: {
    minChapterLength?: number; // in seconds, default 60
    maxChapters?: number; // default 20
    includeDescriptions?: boolean; // default true
    language?: string; // default 'en'
  };
}

export interface GeneratedChapter {
  id: string;
  timestamp: string;
  title: string;
  description?: string;
  startTime: number; // in seconds
  endTime?: number;
  confidence?: number; // 0-1 confidence score
  keywords?: string[];
}

export interface ChapterGenerationResponse {
  videoInfo: YouTubeVideoInfo;
  chapters: GeneratedChapter[];
  metadata: {
    totalChapters: number;
    averageChapterLength: number;
    processingTimeMs: number;
    model: string;
    language: string;
  };
}

// Export Types
export interface ExportRequest {
  chapters: GeneratedChapter[];
  format: ExportFormat;
  videoInfo?: YouTubeVideoInfo;
  options?: ExportOptions;
}

export interface ExportOptions {
  includeTimestamps?: boolean;
  includeDescriptions?: boolean;
  includeVideoInfo?: boolean;
  customTemplate?: string;
  timezone?: string;
}

export type ExportFormat = 
  | 'youtube' 
  | 'text' 
  | 'json' 
  | 'csv' 
  | 'srt' 
  | 'vtt' 
  | 'xml' 
  | 'markdown';

export interface ExportResponse {
  content: string;
  filename: string;
  mimeType: string;
  size: number;
  downloadUrl?: string;
  expiresAt?: string;
}

// API Response Wrappers
export interface APISuccessResponse<T> {
  success: true;
  data: T;
  message?: string;
  timestamp: string;
  version: string;
}

export interface APIErrorResponse {
  success: false;
  error: {
    code: string;
    message: string;
    details?: any;
    stack?: string; // Only in development
  };
  timestamp: string;
  version: string;
}

export type APIResponse<T> = APISuccessResponse<T> | APIErrorResponse;

// Validation Types
export interface ValidationResult {
  isValid: boolean;
  errors: ValidationError[];
  warnings: ValidationWarning[];
}

export interface ValidationError {
  field: string;
  code: string;
  message: string;
  value?: any;
}

export interface ValidationWarning {
  field: string;
  code: string;
  message: string;
  suggestion?: string;
}

// Rate Limiting Types
export interface RateLimitInfo {
  limit: number;
  remaining: number;
  resetTime: number;
  retryAfter?: number;
}

// YouTube API Quota Types
export interface YouTubeQuotaInfo {
  dailyLimit: number;
  used: number;
  remaining: number;
  resetTime: number;
}

// Error Codes
export enum APIErrorCode {
  // Validation Errors
  INVALID_URL = 'INVALID_URL',
  INVALID_VIDEO_ID = 'INVALID_VIDEO_ID',
  INVALID_FORMAT = 'INVALID_FORMAT',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  INVALID_FIELD_TYPE = 'INVALID_FIELD_TYPE',
  
  // YouTube API Errors
  VIDEO_NOT_FOUND = 'VIDEO_NOT_FOUND',
  VIDEO_PRIVATE = 'VIDEO_PRIVATE',
  VIDEO_DELETED = 'VIDEO_DELETED',
  NO_TRANSCRIPT_AVAILABLE = 'NO_TRANSCRIPT_AVAILABLE',
  TRANSCRIPT_DISABLED = 'TRANSCRIPT_DISABLED',
  UNSUPPORTED_LANGUAGE = 'UNSUPPORTED_LANGUAGE',
  
  // Quota & Rate Limiting
  YOUTUBE_QUOTA_EXCEEDED = 'YOUTUBE_QUOTA_EXCEEDED',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  
  // Processing Errors
  CHAPTER_GENERATION_FAILED = 'CHAPTER_GENERATION_FAILED',
  AI_SERVICE_UNAVAILABLE = 'AI_SERVICE_UNAVAILABLE',
  PROCESSING_TIMEOUT = 'PROCESSING_TIMEOUT',
  INSUFFICIENT_CONTENT = 'INSUFFICIENT_CONTENT',
  
  // System Errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR = 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',
  
  // File & Export Errors
  EXPORT_FAILED = 'EXPORT_FAILED',
  UNSUPPORTED_FORMAT = 'UNSUPPORTED_FORMAT',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  DOWNLOAD_EXPIRED = 'DOWNLOAD_EXPIRED'
}

// Request Context (for logging and tracking)
export interface RequestContext {
  requestId: string;
  userId?: string;
  sessionId?: string;
  userAgent?: string;
  ipAddress?: string;
  timestamp: string;
  endpoint: string;
}

// YouTube Transcript API Options
export interface TranscriptFetchOptions {
  languages?: string[]; // Priority order of languages to fetch
  includeAutoGenerated?: boolean; // Whether to include auto-generated transcripts
  fallbackToAnyLanguage?: boolean; // Fallback if preferred language not available
}

// Chapter Generation AI Model Configuration
export interface AIModelConfig {
  model: string; // e.g., 'gpt-4', 'claude-3'
  temperature?: number;
  maxTokens?: number;
  systemPrompt?: string;
  userPromptTemplate?: string;
}

// Webhook Types (for async processing)
export interface WebhookConfig {
  url: string;
  secret?: string;
  events: WebhookEvent[];
}

export enum WebhookEvent {
  TRANSCRIPT_READY = 'transcript.ready',
  CHAPTERS_GENERATED = 'chapters.generated',
  EXPORT_READY = 'export.ready',
  PROCESSING_FAILED = 'processing.failed'
}

export interface WebhookPayload {
  event: WebhookEvent;
  data: any;
  timestamp: string;
  requestId: string;
}

// Analytics and Metrics Types
export interface ProcessingMetrics {
  transcriptFetchTimeMs: number;
  chapterGenerationTimeMs: number;
  totalProcessingTimeMs: number;
  transcriptLength: number;
  chaptersGenerated: number;
  aiModel: string;
  success: boolean;
}

// Cache Configuration
export interface CacheConfig {
  ttl: number; // Time to live in seconds
  key: string;
  strategy: 'memory' | 'redis' | 'both';
}

// Database Models (if using persistence)
export interface VideoRecord {
  id: string;
  videoId: string;
  title: string;
  duration: number;
  channelTitle: string;
  transcriptLanguage?: string;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ChapterRecord {
  id: string;
  videoId: string;
  title: string;
  description?: string;
  startTime: number;
  endTime?: number;
  confidence: number;
  position: number;
  createdAt: string;
}

export interface ProcessingJob {
  id: string;
  videoId: string;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  progress: number;
  error?: string;
  result?: ChapterGenerationResponse;
  createdAt: string;
  updatedAt: string;
  completedAt?: string;
}