import { NextRequest, NextResponse } from 'next/server';
import { execFile } from 'child_process';
import { promisify } from 'util';
import * as path from 'path';
// Note: youtube-transcript is imported dynamically to handle optional dependency
import { 
  APIResponse, 
  YouTubeTranscriptResponse, 
  APIErrorCode,
  ValidationResult,
  TranscriptFetchOptions,
  YouTubeTranscriptSegment
} from '../../../types/api';

// Rate limiting configuration (for future use)
// const RATE_LIMIT_REQUESTS = 100; // requests per hour
// const RATE_LIMIT_WINDOW = 3600; // 1 hour in seconds

// Request body validation schema
interface TranscriptRequest {
  url?: string;
  videoId?: string;
  options?: TranscriptFetchOptions;
}

/**
 * YouTube Transcript API Endpoint
 * Fetches transcript data from YouTube videos
 * 
 * POST /api/youtube/transcript
 * 
 * Body: {
 *   url?: string,           // YouTube video URL
 *   videoId?: string,       // YouTube video ID
 *   options?: {
 *     languages?: string[],          // Language preference order
 *     includeAutoGenerated?: boolean, // Include auto-generated transcripts
 *     fallbackToAnyLanguage?: boolean // Fallback if preferred lang unavailable
 *   }
 * }
 */
export async function POST(request: NextRequest): Promise<NextResponse> {
  const startTime = Date.now();
  const requestId = generateRequestId();
  let body: TranscriptRequest;
  let videoId: string | undefined;

  // Note: We use Python script for transcript fetching, so YouTube API key is optional

  try {
    // Parse and validate request body
    body = await request.json();
    const validation = validateTranscriptRequest(body);
    
    if (!validation.isValid) {
      return createErrorResponse(
        APIErrorCode.INVALID_FIELD_TYPE,
        'Validation failed',
        validation.errors,
        400
      );
    }

    // Extract video ID from URL or use provided videoId
    videoId = body.videoId || extractVideoIdFromUrl(body.url!) || undefined;
    if (!videoId) {
      return createErrorResponse(
        APIErrorCode.INVALID_VIDEO_ID,
        'Invalid YouTube URL or video ID',
        null,
        400
      );
    }

    // Check rate limiting
    const rateLimitCheck = await checkRateLimit(request);
    if (!rateLimitCheck.allowed) {
      return createErrorResponse(
        APIErrorCode.RATE_LIMIT_EXCEEDED,
        'Rate limit exceeded',
        { retryAfter: rateLimitCheck.retryAfter },
        429
      );
    }

    // Check YouTube API quota
    const quotaCheck = await checkYouTubeQuota();
    if (!quotaCheck.available) {
      return createErrorResponse(
        APIErrorCode.YOUTUBE_QUOTA_EXCEEDED,
        'YouTube API quota exceeded',
        { resetTime: quotaCheck.resetTime },
        503
      );
    }

    // Attempt to fetch transcript (this will also get basic video info)
    const transcriptData = await fetchTranscript(videoId, body.options);
    
    if (!transcriptData) {
      return createErrorResponse(
        APIErrorCode.NO_TRANSCRIPT_AVAILABLE,
        'No transcript available for this video',
        { 
          videoId,
          suggestions: [
            'Try uploading an SRT file manually',
            'Check if the video has captions enabled',
            'Contact the video creator to enable captions'
          ]
        },
        404
      );
    }

    // Prepare successful response
    const response: YouTubeTranscriptResponse = {
      videoId,
      title: transcriptData.title || `Video ${videoId}`,
      duration: transcriptData.duration || Math.max(...transcriptData.segments.map(s => s.start + s.duration)),
      segments: transcriptData.segments,
      language: transcriptData.language,
      isAutoGenerated: transcriptData.isAutoGenerated
    };

    // Log success metrics
    await logProcessingMetrics({
      requestId,
      videoId,
      transcriptFetchTimeMs: Date.now() - startTime,
      transcriptLength: transcriptData.segments.length,
      success: true
    });

    return createSuccessResponse(response);

  } catch (error) {
    console.error('Transcript fetch error:', error);
    
    // Log error metrics
    await logProcessingMetrics({
      requestId,
      videoId: videoId || 'unknown',
      transcriptFetchTimeMs: Date.now() - startTime,
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    });

    if (error instanceof YouTubeAPIError) {
      return createErrorResponse(
        error.code,
        error.message,
        error.details,
        error.statusCode
      );
    }

    return createErrorResponse(
      APIErrorCode.INTERNAL_SERVER_ERROR,
      'Failed to fetch transcript',
      process.env.NODE_ENV === 'development' ? { stack: error } : null,
      500
    );
  }
}

// Environment validation function (unused for now, but kept for future use)
// function validateEnvironment(): { isValid: boolean; missing: string[] } {
//   const missing: string[] = [];
//   
//   if (!process.env.YOUTUBE_API_KEY) {
//     missing.push('YOUTUBE_API_KEY');
//   }
//   
//   // Optional: validate API key format (should be ~39 characters starting with AIza)
//   if (process.env.YOUTUBE_API_KEY && !process.env.YOUTUBE_API_KEY.startsWith('AIza')) {
//     console.warn('YouTube API key format appears invalid - should start with "AIza"');
//   }
//   
//   return {
//     isValid: missing.length === 0,
//     missing
//   };
// }

/**
 * Validate transcript request body
 */
function validateTranscriptRequest(body: TranscriptRequest): ValidationResult {
  const errors = [];
  const warnings = [];

  // Must have either URL or videoId
  if (!body.url && !body.videoId) {
    errors.push({
      field: 'url_or_videoId',
      code: 'MISSING_REQUIRED',
      message: 'Either URL or videoId is required',
      value: null
    });
  }

  // Validate URL format if provided
  if (body.url && !isValidYouTubeUrl(body.url)) {
    errors.push({
      field: 'url',
      code: 'INVALID_FORMAT',
      message: 'Invalid YouTube URL format',
      value: body.url
    });
  }

  // Validate videoId format if provided
  if (body.videoId && !isValidVideoId(body.videoId)) {
    errors.push({
      field: 'videoId',
      code: 'INVALID_FORMAT',
      message: 'Invalid YouTube video ID format',
      value: body.videoId
    });
  }

  // Validate options if provided
  if (body.options) {
    if (body.options.languages && !Array.isArray(body.options.languages)) {
      errors.push({
        field: 'options.languages',
        code: 'INVALID_TYPE',
        message: 'Languages must be an array of strings',
        value: body.options.languages
      });
    }

    if (body.options.languages && body.options.languages.length > 10) {
      warnings.push({
        field: 'options.languages',
        code: 'TOO_MANY_LANGUAGES',
        message: 'Maximum 10 languages supported',
        suggestion: 'Limit to top 3-5 preferred languages for better performance'
      });
    }
  }

  return {
    isValid: errors.length === 0,
    errors,
    warnings
  };
}

/**
 * Extract YouTube video ID from various URL formats
 */
function extractVideoIdFromUrl(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/,
    /youtube\.com\/v\/([a-zA-Z0-9_-]{11})/,
    /youtube\.com\/watch\?.*v=([a-zA-Z0-9_-]{11})/
  ];

  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) return match[1];
  }

  return null;
}

/**
 * Validate YouTube URL format
 */
function isValidYouTubeUrl(url: string): boolean {
  const youtubeRegex = /^(https?:\/\/)?(www\.)?(youtube\.com|youtu\.be)\/.+/;
  return youtubeRegex.test(url);
}

/**
 * Validate YouTube video ID format
 */
function isValidVideoId(videoId: string): boolean {
  return /^[a-zA-Z0-9_-]{11}$/.test(videoId);
}

// fetchVideoInfo function removed to eliminate unused code warnings
// (was fetching video information from YouTube Data API v3)

/**
 * Fetch transcript using Python script
 */
async function fetchTranscript(
  videoId: string, 
  options?: TranscriptFetchOptions
): Promise<{ segments: YouTubeTranscriptSegment[]; language: string; isAutoGenerated: boolean; title?: string; duration?: number } | null> {
  
  try {
    console.log(`Attempting to fetch transcript for video ID: ${videoId}`);
    
    // Use the same approach as the chapter generation endpoint
    const execFileAsync = promisify(execFile);
    
    const pythonScript = path.join(process.cwd(), 'api_caps.py');
    // Use system Python in production (Railway), venv Python in development
    const pythonPath = process.env.NODE_ENV === 'production' 
      ? 'python3' 
      : path.join(process.cwd(), 'venv', 'bin', 'python3');
    
    console.log(`Executing Python script: ${pythonPath} ${pythonScript} ${videoId}`);
    
    const { stdout, stderr } = await execFileAsync(pythonPath, [pythonScript, videoId], {
      timeout: 30000, // 30 second timeout
      maxBuffer: 10 * 1024 * 1024 // 10MB buffer for large transcripts
    });

    if (stderr && stderr.trim()) {
      console.warn('Python script stderr:', stderr);
    }

    // Parse the JSON output from the Python script
    const transcriptData = JSON.parse(stdout);
    
    if (!transcriptData.success) {
      console.error('Python script error:', transcriptData.error);
      return null;
    }
    
    // Convert Python script output to expected format
    const segments: YouTubeTranscriptSegment[] = transcriptData.transcript.map((segment: { text: string; start: number; duration?: number }) => ({
      text: segment.text,
      start: segment.start,
      duration: segment.duration || 1
    }));

    return {
      segments,
      language: transcriptData.language || 'en',
      isAutoGenerated: true,
      title: transcriptData.title,
      duration: transcriptData.duration
    };

  } catch (error) {
    console.error('Transcript fetch failed with error:', error);
    console.error('Error details:', {
      name: error instanceof Error ? error.name : 'Unknown',
      message: error instanceof Error ? error.message : 'Unknown error',
      videoId
    });
    
    // If main method fails, try fallback
    console.log('Attempting fallback transcript fetch...');
    return await fetchTranscriptFallback(videoId, options);
  }
}

/**
 * Fallback transcript fetching method
 */
async function fetchTranscriptFallback(
  videoId: string, 
  options?: TranscriptFetchOptions
): Promise<{ segments: YouTubeTranscriptSegment[]; language: string; isAutoGenerated: boolean; title?: string; duration?: number } | null> {
  
  try {
    console.log(`Fallback: Attempting direct YouTube timedtext API for video: ${videoId}`);
    
    // Alternative method: Try to fetch transcript directly from YouTube's internal API
    const timedTextUrl = `https://www.youtube.com/api/timedtext?v=${videoId}&lang=${options?.languages?.[0] || 'en'}&fmt=json3`;
    
    console.log(`Fallback: Fetching from URL: ${timedTextUrl}`);
    
    const response = await fetch(timedTextUrl, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (compatible; ChapterSmith/1.0)'
      }
    });
    
    console.log(`Fallback: Response status: ${response.status}`);

    if (!response.ok) {
      console.log(`Fallback: Request failed with status ${response.status}. Trying alternative method...`);
      
      // Try another fallback - check if captions are available
      const captionsUrl = `https://www.youtube.com/watch?v=${videoId}`;
      console.log(`Fallback: Checking captions availability at: ${captionsUrl}`);
      
      // If that fails, return mock data for development
      if (process.env.NODE_ENV === 'development') {
        console.log('Fallback: Returning mock data for development');
        return {
          segments: [
            { text: "Welcome to this tutorial on building YouTube chapter generators", start: 0, duration: 4.5 },
            { text: "Today we'll be learning how to extract transcripts", start: 4.5, duration: 3.2 },
            { text: "and automatically generate chapter markers", start: 7.7, duration: 2.8 },
            { text: "First, we need to set up our development environment", start: 10.5, duration: 4.0 },
            { text: "This includes installing Node.js and the necessary packages", start: 14.5, duration: 3.8 },
            { text: "Next, we'll create our API endpoints for transcript fetching", start: 18.3, duration: 4.2 },
            { text: "The chapter generation will use AI to analyze content", start: 22.5, duration: 3.9 },
            { text: "Finally, we'll implement export functionality in multiple formats", start: 26.4, duration: 4.1 }
          ],
          language: 'en',
          isAutoGenerated: true,
          title: `Development Video ${videoId}`,
          duration: 30.5
        };
      }
      return null;
    }

    const data = await response.json();
    console.log(`Fallback: Received data structure:`, { hasEvents: !!data.events, eventCount: data.events?.length || 0 });
    
    if (!data.events) {
      console.log('Fallback: No events found in response data');
      return null;
    }

    // Parse YouTube's timedtext format
    const segments: YouTubeTranscriptSegment[] = [];
    
    data.events.forEach((event: { tStartMs: number; dDurationMs?: number; segs?: Array<{ utf8?: string }> }) => {
      if (event.segs) {
        event.segs.forEach((seg: { utf8?: string }) => {
          if (seg.utf8) {
            segments.push({
              text: seg.utf8,
              start: event.tStartMs / 1000,
              duration: (event.dDurationMs || 3000) / 1000
            });
          }
        });
      }
    });

    return {
      segments,
      language: options?.languages?.[0] || 'en',
      isAutoGenerated: true,
      title: `Video ${videoId}`,
      duration: Math.max(...segments.map(s => s.start + s.duration))
    };

  } catch (error) {
    console.error('Fallback transcript fetch failed:', error);
    console.error('Fallback error details:', {
      name: error instanceof Error ? error.name : 'Unknown',
      message: error instanceof Error ? error.message : 'Unknown error',
      videoId
    });
    return null;
  }
}

/**
 * Check rate limiting for the current request
 */
async function checkRateLimit(request: NextRequest): Promise<{ allowed: boolean; retryAfter?: number }> {
  // Get client identifier (IP address or user ID)
  getClientIdentifier(request);
  
  // In a real implementation, you would use Redis or similar for rate limiting
  // This is a simplified in-memory example
  
  return { allowed: true }; // Mock implementation
}

/**
 * Check YouTube API quota availability
 */
async function checkYouTubeQuota(): Promise<{ available: boolean; resetTime?: number }> {
  // In a real implementation, track quota usage in database/cache
  return { available: true }; // Mock implementation
}

// parseDurationToSeconds function removed to eliminate unused code warnings
// (was parsing ISO 8601 duration to seconds)

/**
 * Generate unique request ID
 */
function generateRequestId(): string {
  return `req_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
}

/**
 * Get client identifier for rate limiting
 */
function getClientIdentifier(request: NextRequest): string {
  // Try to get user ID from session/auth
  // Fallback to IP address
  return request.headers.get('x-forwarded-for') || request.headers.get('x-real-ip') || 'anonymous';
}

/**
 * Log processing metrics
 */
async function logProcessingMetrics(metrics: {
  requestId: string;
  videoId: string;
  transcriptFetchTimeMs: number;
  transcriptLength?: number;
  success: boolean;
  error?: string;
}): Promise<void> {
  // In production, send to analytics service, database, or monitoring system
  console.log('Processing metrics:', metrics);
}

/**
 * Create standardized success response
 */
function createSuccessResponse<T>(data: T): NextResponse {
  const response: APIResponse<T> = {
    success: true,
    data,
    timestamp: new Date().toISOString(),
    version: '1.0.0'
  };
  
  return NextResponse.json(response, { status: 200 });
}

/**
 * Create standardized error response
 */
function createErrorResponse(
  code: APIErrorCode,
  message: string,
  details: unknown = null,
  status: number = 500
): NextResponse {
  const response: APIResponse<never> = {
    success: false,
    error: {
      code,
      message,
      details,
      ...(process.env.NODE_ENV === 'development' && { stack: new Error().stack })
    },
    timestamp: new Date().toISOString(),
    version: '1.0.0'
  };
  
  return NextResponse.json(response, { status });
}

/**
 * Custom YouTube API Error class
 */
class YouTubeAPIError extends Error {
  constructor(
    public code: APIErrorCode,
    message: string,
    public details: unknown = null,
    public statusCode: number = 500
  ) {
    super(message);
    this.name = 'YouTubeAPIError';
  }
}